
package org.eclipse.simpl.rrs.ui.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.eclipse.simpl.rrs.ui.RRSUIPlugIn;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RRSMetaData", targetNamespace = "http://webservices.rrs.simpl.org/", wsdlLocation = "http://localhost:8080/ode/processes/RRSMetaDataService.RRSMetaDataServicePort?wsdl")
public class RRSMetaData
    extends Service
{
	
	private final static String RRS_MD_WSDL = RRSUIPlugIn.getDefault().getPreferenceStore().getString("RRS_MD_ADDRESS");

    private final static URL RRSMETADATA_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.eclipse.simpl.rrs.ui.client.RRSMetaData.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = RRSMetaData.class.getResource(".");
            url = new URL(baseUrl, RRS_MD_WSDL);
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '"+RRS_MD_WSDL+"', retrying as a local file");
            logger.warning(e.getMessage());
        }
        RRSMETADATA_WSDL_LOCATION = url;
    }

    public RRSMetaData(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RRSMetaData() {
        super(RRSMETADATA_WSDL_LOCATION, new QName("http://webservices.rrs.simpl.org/", "RRSMetaDataService"));
    }

    /**
     * 
     * @return
     *     returns RRSMetaDataService
     */
    @WebEndpoint(name = "RRSMetaDataServicePort")
    public RRSMetaDataService getRRSMetaDataServicePort() {
        return super.getPort(new QName("http://webservices.rrs.simpl.org/", "RRSMetaDataServicePort"), RRSMetaDataService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RRSMetaDataService
     */
    @WebEndpoint(name = "RRSMetaDataServicePort")
    public RRSMetaDataService getRRSMetaDataServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.rrs.simpl.org/", "RRSMetaDataServicePort"), RRSMetaDataService.class, features);
    }

}
