
package localhost._8080;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ConnectionException", targetNamespace = "http://webservices.core.simpl.org/")
public class ConnectionException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private org.simpl.core.webservices.ConnectionException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ConnectionException(String message, org.simpl.core.webservices.ConnectionException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ConnectionException(String message, org.simpl.core.webservices.ConnectionException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.simpl.core.webservices.ConnectionException
     */
    public org.simpl.core.webservices.ConnectionException getFaultInfo() {
        return faultInfo;
    }

}
