
package localhost._8080;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DatasourceService", targetNamespace = "http://localhost:8080", wsdlLocation = "file:/C:/eclipse/workspace/SIMPLCore/DatasourceService.wsdl")
public class DatasourceService_Service
    extends Service
{

    private final static URL DATASOURCESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(localhost._8080.DatasourceService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = localhost._8080.DatasourceService_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/eclipse/workspace/SIMPLCore/DatasourceService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/eclipse/workspace/SIMPLCore/DatasourceService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DATASOURCESERVICE_WSDL_LOCATION = url;
    }

    public DatasourceService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DatasourceService_Service() {
        super(DATASOURCESERVICE_WSDL_LOCATION, new QName("http://localhost:8080", "DatasourceService"));
    }

    /**
     * 
     * @return
     *     returns DatasourceService
     */
    @WebEndpoint(name = "DatasourceServicePort")
    public DatasourceService getDatasourceServicePort() {
        return super.getPort(new QName("http://localhost:8080", "DatasourceServicePort"), DatasourceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DatasourceService
     */
    @WebEndpoint(name = "DatasourceServicePort")
    public DatasourceService getDatasourceServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost:8080", "DatasourceServicePort"), DatasourceService.class, features);
    }

}
