
package localhost._8080;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.simpl.core.webservices.LinkedHashMap;
import org.simpl.core.webservices.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AdministrationService", targetNamespace = "http://webservices.core.simpl.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AdministrationService {


    /**
     * 
     * @param schema
     * @param arg3
     * @param settingName
     * @param table
     * @return
     *     returns boolean
     */
    @WebMethod(action = "saveSettings")
    @WebResult(partName = "return")
    public boolean saveSettings(
        @WebParam(name = "schema", partName = "schema")
        String schema,
        @WebParam(name = "table", partName = "table")
        String table,
        @WebParam(name = "settingName", partName = "settingName")
        String settingName,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3);

    /**
     * 
     * @param schema
     * @param settingName
     * @param table
     * @return
     *     returns org.simpl.core.webservices.LinkedHashMap
     */
    @WebMethod(action = "loadSettings")
    @WebResult(partName = "return")
    public LinkedHashMap loadSettings(
        @WebParam(name = "schema", partName = "schema")
        String schema,
        @WebParam(name = "table", partName = "table")
        String table,
        @WebParam(name = "settingName", partName = "settingName")
        String settingName);

}
