
package org.simpl.resource.discovery.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ResourceDiscoveryService", targetNamespace = "http://discovery.resource.simpl.org/", wsdlLocation = "http://localhost:8080/axis2/services/ResourceDiscoveryService.ResourceDiscoveryPort?wsdl")
public class ResourceDiscoveryService
    extends Service
{

    private final static URL RESOURCEDISCOVERYSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.simpl.resource.discovery.client.ResourceDiscoveryService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.simpl.resource.discovery.client.ResourceDiscoveryService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/axis2/services/ResourceDiscoveryService.ResourceDiscoveryPort?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/axis2/services/ResourceDiscoveryService.ResourceDiscoveryPort?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        RESOURCEDISCOVERYSERVICE_WSDL_LOCATION = url;
    }

    public ResourceDiscoveryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ResourceDiscoveryService() {
        super(RESOURCEDISCOVERYSERVICE_WSDL_LOCATION, new QName("http://discovery.resource.simpl.org/", "ResourceDiscoveryService"));
    }

    /**
     * 
     * @return
     *     returns ResourceDiscovery
     */
    @WebEndpoint(name = "ResourceDiscoveryPort")
    public ResourceDiscovery getResourceDiscoveryPort() {
        return super.getPort(new QName("http://discovery.resource.simpl.org/", "ResourceDiscoveryPort"), ResourceDiscovery.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ResourceDiscovery
     */
    @WebEndpoint(name = "ResourceDiscoveryPort")
    public ResourceDiscovery getResourceDiscoveryPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://discovery.resource.simpl.org/", "ResourceDiscoveryPort"), ResourceDiscovery.class, features);
    }

}
