
package org.simpl.resource.discovery.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.simpl.resource.management.data.DataSource;
import org.simpl.resource.management.data.LateBinding;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ResourceDiscovery", targetNamespace = "http://discovery.resource.simpl.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ResourceDiscovery {


    /**
     * 
     * @param arg0
     * @return
     *     returns org.simpl.resource.discovery.client.DataSource
     */
    @WebMethod(action = "findDataSource")
    @WebResult(partName = "return")
    public DataSource findDataSource(
        @WebParam(name = "arg0", partName = "arg0")
        LateBinding arg0);

}
