
package org.simpl.core.webservices.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.simpl.resource.management.client.DataSource;
import org.simpl.resource.management.client.LateBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DatasourceService", targetNamespace = "http://webservices.core.simpl.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DatasourceService {


    /**
     * 
     * @param dataSource
     * @param filter
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod(action = "getMetaData")
    @WebResult(partName = "return")
    public String getMetaData(
        @WebParam(name = "dataSource", partName = "dataSource")
        DataSource dataSource,
        @WebParam(name = "filter", partName = "filter")
        String filter)
        throws Exception_Exception
    ;

    /**
     * 
     * @param statement
     * @param dataSource
     * @param lateBinding
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod(action = "executeStatementByDataSourceObject")
    @WebResult(partName = "return")
    public boolean executeStatementByDataSourceObject(
        @WebParam(name = "dataSource", partName = "dataSource")
        DataSource dataSource,
        @WebParam(name = "statement", partName = "statement")
        String statement,
        @WebParam(name = "lateBinding", partName = "lateBinding")
        LateBinding lateBinding)
        throws Exception_Exception
    ;

    /**
     * 
     * @param statement
     * @param lateBinding
     * @param dataSourceDescriptor
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod(action = "executeStatementByDataSourceDescriptor")
    @WebResult(partName = "return")
    public boolean executeStatementByDataSourceDescriptor(
        @WebParam(name = "dataSourceDescriptor", partName = "dataSourceDescriptor")
        String dataSourceDescriptor,
        @WebParam(name = "statement", partName = "statement")
        String statement,
        @WebParam(name = "lateBinding", partName = "lateBinding")
        LateBinding lateBinding)
        throws Exception_Exception
    ;

    /**
     * 
     * @param statement
     * @param dataSource
     * @param lateBinding
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod(action = "retrieveDataByDataSourceObject")
    @WebResult(partName = "return")
    public String retrieveDataByDataSourceObject(
        @WebParam(name = "dataSource", partName = "dataSource")
        DataSource dataSource,
        @WebParam(name = "statement", partName = "statement")
        String statement,
        @WebParam(name = "lateBinding", partName = "lateBinding")
        LateBinding lateBinding)
        throws Exception_Exception
    ;

    /**
     * 
     * @param statement
     * @param dataSource
     * @param lateBinding
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod(action = "retrieveDataByDataSourceDescriptor")
    @WebResult(partName = "return")
    public String retrieveDataByDataSourceDescriptor(
        @WebParam(name = "dataSource", partName = "dataSource")
        String dataSource,
        @WebParam(name = "statement", partName = "statement")
        String statement,
        @WebParam(name = "lateBinding", partName = "lateBinding")
        LateBinding lateBinding)
        throws Exception_Exception
    ;

    /**
     * 
     * @param dataSource
     * @param lateBinding
     * @param dataObject
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod(action = "writeBackByDataSourceObject")
    @WebResult(partName = "return")
    public boolean writeBackByDataSourceObject(
        @WebParam(name = "dataSource", partName = "dataSource")
        DataSource dataSource,
        @WebParam(name = "dataObject", partName = "dataObject")
        String dataObject,
        @WebParam(name = "lateBinding", partName = "lateBinding")
        LateBinding lateBinding)
        throws Exception_Exception
    ;

    /**
     * 
     * @param lateBinding
     * @param dataObject
     * @param dataSourceDescriptor
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod(action = "writeBackByDataSourceDescriptor")
    @WebResult(partName = "return")
    public boolean writeBackByDataSourceDescriptor(
        @WebParam(name = "dataSourceDescriptor", partName = "dataSourceDescriptor")
        String dataSourceDescriptor,
        @WebParam(name = "dataObject", partName = "dataObject")
        String dataObject,
        @WebParam(name = "lateBinding", partName = "lateBinding")
        LateBinding lateBinding)
        throws Exception_Exception
    ;

    /**
     * 
     * @param dataSource
     * @param lateBinding
     * @param target
     * @param dataObject
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod(action = "writeDataByDataSourceObjectObject")
    @WebResult(partName = "return")
    public boolean writeDataByDataSourceObject(
        @WebParam(name = "dataSource", partName = "dataSource")
        DataSource dataSource,
        @WebParam(name = "dataObject", partName = "dataObject")
        String dataObject,
        @WebParam(name = "target", partName = "target")
        String target,
        @WebParam(name = "lateBinding", partName = "lateBinding")
        LateBinding lateBinding)
        throws Exception_Exception
    ;

    /**
     * 
     * @param lateBinding
     * @param target
     * @param dataObject
     * @param dataSourceDescriptor
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod(action = "writeDataByDataSourceDescriptor")
    @WebResult(partName = "return")
    public boolean writeDataByDataSourceDescriptor(
        @WebParam(name = "dataSourceDescriptor", partName = "dataSourceDescriptor")
        String dataSourceDescriptor,
        @WebParam(name = "dataObject", partName = "dataObject")
        String dataObject,
        @WebParam(name = "target", partName = "target")
        String target,
        @WebParam(name = "lateBinding", partName = "lateBinding")
        LateBinding lateBinding)
        throws Exception_Exception
    ;

    /**
     * 
     * @param statement
     * @param dataSource
     * @param lateBinding
     * @param target
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod(action = "depositDataByDataSourceObject")
    @WebResult(partName = "return")
    public boolean depositDataByDataSourceObject(
        @WebParam(name = "dataSource", partName = "dataSource")
        DataSource dataSource,
        @WebParam(name = "statement", partName = "statement")
        String statement,
        @WebParam(name = "target", partName = "target")
        String target,
        @WebParam(name = "lateBinding", partName = "lateBinding")
        LateBinding lateBinding)
        throws Exception_Exception
    ;

    /**
     * 
     * @param statement
     * @param lateBinding
     * @param target
     * @param dataSourceDescriptor
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod(action = "depositDataByDataSourceDescriptor")
    @WebResult(partName = "return")
    public boolean depositDataByDataSourceDescriptor(
        @WebParam(name = "dataSourceDescriptor", partName = "dataSourceDescriptor")
        String dataSourceDescriptor,
        @WebParam(name = "statement", partName = "statement")
        String statement,
        @WebParam(name = "target", partName = "target")
        String target,
        @WebParam(name = "lateBinding", partName = "lateBinding")
        LateBinding lateBinding)
        throws Exception_Exception
    ;

    /**
     * 
     * @param dataSource
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod(action = "getMetaDataSchema")
    @WebResult(partName = "return")
    public String getMetaDataSchema(
        @WebParam(name = "dataSource", partName = "dataSource")
        DataSource dataSource)
        throws Exception_Exception
    ;

}
