
package org.simpl.resource.framework.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ResourceFramework", targetNamespace = "http://framework.resource.simpl.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ResourceFramework {


    /**
     * 
     * @return
     *     returns org.simpl.resource.framework.client.DataSourceList
     * @throws Exception_Exception
     */
    @WebMethod(action = "getAllDataSources")
    @WebResult(partName = "return")
    public DataSourceList getAllDataSources()
        throws Exception_Exception
    ;

    /**
     * 
     * @param type
     * @return
     *     returns org.simpl.resource.framework.client.DataSourceList
     * @throws Exception_Exception
     */
    @WebMethod(action = "getDataSourcesByType")
    @WebResult(partName = "return")
    public DataSourceList getDataSourcesByType(
        @WebParam(name = "type", partName = "type")
        String type)
        throws Exception_Exception
    ;

    /**
     * 
     * @param subType
     * @param type
     * @return
     *     returns org.simpl.resource.framework.client.DataSourceList
     * @throws Exception_Exception
     */
    @WebMethod(action = "getDataSourcesByTypeAndSubtype")
    @WebResult(partName = "return")
    public DataSourceList getDataSourcesByTypeAndSubtype(
        @WebParam(name = "type", partName = "type")
        String type,
        @WebParam(name = "subType", partName = "subType")
        String subType)
        throws Exception_Exception
    ;

    /**
     * 
     * @param name
     * @return
     *     returns org.simpl.resource.framework.client.DataSourceList
     * @throws Exception_Exception
     */
    @WebMethod(action = "getDataSourcesByName")
    @WebResult(partName = "return")
    public DataSourceList getDataSourcesByName(
        @WebParam(name = "name", partName = "name")
        String name)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod(action = "createResourceFrameworkTables")
    @WebResult(partName = "return")
    public boolean createResourceFrameworkTables()
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod(action = "addDataSource")
    @WebResult(partName = "return")
    public boolean addDataSource(
        @WebParam(name = "arg0", partName = "arg0")
        DataSource arg0)
        throws Exception_Exception
    ;

}
