
package org.eclipse.simpl.communication.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AdministrationService", targetNamespace = "http://webservices.core.simpl.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface AdministrationService {


    /**
     * 
     * @param schema
     * @param settingName
     * @param settings
     * @param table
     * @return
     *     returns boolean
     */
    @WebMethod(action = "saveSettings")
    @WebResult(partName = "return")
    public boolean saveSettings(
        @WebParam(name = "schema", partName = "schema")
        String schema,
        @WebParam(name = "table", partName = "table")
        String table,
        @WebParam(name = "settingName", partName = "settingName")
        String settingName,
        @WebParam(name = "settings", partName = "settings")
        String settings);

    /**
     * 
     * @param schema
     * @param settingName
     * @param table
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "loadSettings")
    @WebResult(partName = "return")
    public String loadSettings(
        @WebParam(name = "schema", partName = "schema")
        String schema,
        @WebParam(name = "table", partName = "table")
        String table,
        @WebParam(name = "settingName", partName = "settingName")
        String settingName);

}
