
package org.simpl.rrs.webservices.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RRSMetaDataService", targetNamespace = "http://webservices.rrs.simpl.org/", wsdlLocation = "http://localhost:8080/axis2/services/RRSMetaDataService.RRSMetaDataServicePort?wsdl")
public class RRSMetaDataService_Service
    extends Service
{

    private final static URL RRSMETADATASERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.simpl.rrs.webservices.client.RRSMetaDataService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.simpl.rrs.webservices.client.RRSMetaDataService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/axis2/services/RRSMetaDataService.RRSMetaDataServicePort?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/axis2/services/RRSMetaDataService.RRSMetaDataServicePort?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        RRSMETADATASERVICE_WSDL_LOCATION = url;
    }

    public RRSMetaDataService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RRSMetaDataService_Service() {
        super(RRSMETADATASERVICE_WSDL_LOCATION, new QName("http://webservices.rrs.simpl.org/", "RRSMetaDataService"));
    }

    /**
     * 
     * @return
     *     returns RRSMetaDataService
     */
    @WebEndpoint(name = "RRSMetaDataServicePort")
    public RRSMetaDataService getRRSMetaDataServicePort() {
        return super.getPort(new QName("http://webservices.rrs.simpl.org/", "RRSMetaDataServicePort"), RRSMetaDataService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RRSMetaDataService
     */
    @WebEndpoint(name = "RRSMetaDataServicePort")
    public RRSMetaDataService getRRSMetaDataServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.rrs.simpl.org/", "RRSMetaDataServicePort"), RRSMetaDataService.class, features);
    }

}
