
package org.simpl.core.webservices.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SIMPLCoreService", targetNamespace = "http://webservices.core.simpl.org/", wsdlLocation = "http://localhost:8080/ode/processes/SIMPLCoreService.SIMPLCoreServicePort?wsdl")
public class SIMPLCoreService_Service
    extends Service
{

    private final static URL SIMPLCORESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.simpl.core.webservices.client.SIMPLCoreService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.simpl.core.webservices.client.SIMPLCoreService_Service.class.getResource(".");
            url = new URL(baseUrl, SIMPLCoreServiceClient.serviceAddress);
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '" + SIMPLCoreServiceClient.serviceAddress + "', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SIMPLCORESERVICE_WSDL_LOCATION = url;
    }

    public SIMPLCoreService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIMPLCoreService_Service() {
        super(SIMPLCORESERVICE_WSDL_LOCATION, new QName("http://webservices.core.simpl.org/", "SIMPLCoreService"));
    }

    /**
     * 
     * @return
     *     returns SIMPLCoreService
     */
    @WebEndpoint(name = "SIMPLCoreServicePort")
    public SIMPLCoreService getSIMPLCoreServicePort() {
        return super.getPort(new QName("http://webservices.core.simpl.org/", "SIMPLCoreServicePort"), SIMPLCoreService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMPLCoreService
     */
    @WebEndpoint(name = "SIMPLCoreServicePort")
    public SIMPLCoreService getSIMPLCoreServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.core.simpl.org/", "SIMPLCoreServicePort"), SIMPLCoreService.class, features);
    }

}
