
package org.simpl.uddi.utils;

import java.io.FileNotFoundException;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.simpl.uddi.UddiWebConfig;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DatasourceService", targetNamespace = "http://webservices.core.simpl.org/", wsdlLocation = "http://localhost:8080/ode/processes/DatasourceService.DatasourceServicePort?wsdl")
public class DatasourceService_Service
    extends Service
{
    private static String DSS_WSDL_ADDRESS = null;
    
    private static URL DATASOURCESERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
        	DSS_WSDL_ADDRESS = UddiWebConfig.getInstance().getDsAddress(); 
            URL baseUrl;
            baseUrl = DatasourceService_Service.class.getResource(".");
            url = new URL(baseUrl, DSS_WSDL_ADDRESS);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        } catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        DATASOURCESERVICE_WSDL_LOCATION = url;
    }

    public DatasourceService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DatasourceService_Service() {
    	super(DATASOURCESERVICE_WSDL_LOCATION, new QName("http://webservices.core.simpl.org/", "DatasourceService"));
    }
    
    public static void refresh() {
    	URL url = null;
        try {
        	DSS_WSDL_ADDRESS = UddiWebConfig.getInstance().getDsAddress(); 
            URL baseUrl;
            baseUrl = DatasourceService_Service.class.getResource(".");
            url = new URL(baseUrl, DSS_WSDL_ADDRESS);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        } catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        DATASOURCESERVICE_WSDL_LOCATION = url;
        try {
        	DSS_WSDL_ADDRESS = UddiWebConfig.getInstance().getDsAddress(); 
            URL baseUrl;
            baseUrl = DatasourceService_Service.class.getResource(".");
            url = new URL(baseUrl, DSS_WSDL_ADDRESS);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        } catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        DATASOURCESERVICE_WSDL_LOCATION = url;
    	
    }

    /**
     * 
     * @return
     *     returns DatasourceService
     */
    @WebEndpoint(name = "DatasourceServicePort")
    public DatasourceService getDatasourceServicePort() {
        return super.getPort(new QName("http://webservices.core.simpl.org/", "DatasourceServicePort"), DatasourceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DatasourceService
     */
    @WebEndpoint(name = "DatasourceServicePort")
    public DatasourceService getDatasourceServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.core.simpl.org/", "DatasourceServicePort"), DatasourceService.class, features);
    }

}
